### ISSUE TITLE
Feature/fix retina image generation

### ISSUE THREAD

**Issue by koyan** [greenpeace/planet4-plugin-blocks#122]
Initiated by https://github.com/greenpeace/planet4-plugin-blocks/pull/121

As Ray wrote there: 
> Help wanted:

    modifying other plugin block classes and templates
    registering standard image sizes with add_image_size
    removing hardcoded '1024,768' maximum image size in line wp_calculate_image_srcset(['1024', '768']

**Comment by kirdia** [comment]
Removed timber resizing from all twig templates used in this repo.

Used wordpress img srcset and sizes functions (_wp_get_attachment_image_srcset_, _wp_calculate_image_sizes_) to generate img srcset & sizes attributes used in an img tag in templates.

### Blocks with image tags that have srcset attribute.
Carousel 
Carousel Header
Carousel Split
Media block

### Blocks with image tags that do not have srcset attribute and a single image size was used.
_Default wordpress image sizes were used._
Campaign thumbnail - medium_large
Content four column - medium
Content three column - medium_large
Static four column - thumbnail
Tasks - medium


_Default wordpress image sizes._
'thumbnail'          - Thumbnail (default 150px x 150px max)
'medium'            -  Medium resolution (default 300px x 300px max)
'medium_large'  -  Medium Large resolution (default 768px x 0px max)
'large'                 -  Large resolution (default 1024px x 1024px max)
'full'                    -  Original image resolution (unmodified)


Resolved with the below pull requests.
[135](https://github.com/greenpeace/planet4-plugin-blocks/pull/135)
[137](https://github.com/greenpeace/planet4-plugin-blocks/pull/137)
[138](https://github.com/greenpeace/planet4-plugin-blocks/pull/138)
[140](https://github.com/greenpeace/planet4-plugin-blocks/pull/140)
[141](https://github.com/greenpeace/planet4-plugin-blocks/pull/141)
