### ISSUE TITLE
Update CircleCI configuration to version 2.0

### ISSUE THREAD

**Issue by 27Bslash6** [greenpeace/planet4-plugin-blocks#335]
See: https://circleci.com/gh/greenpeace/planet4-plugin-blocks/6

`This project is currently running on CircleCI 1.0 which will no longer be supported after August 31, 2018. Please start migrating this project to CircleCI 2.0`

@angtheod I guess that when `wp scaffold` was run, it was with a version of wp-cli from before this PR was merged: https://github.com/wp-cli/scaffold-command/pull/115

Perhaps try rebuilding the configuration with a recent version of wp-cli

Builds on Circle v1.0 will stop working on August 31

**Comment by angtheod** [comment]
Oh, didn't know that, sorry!
